dist: xenial
language: julia
os: [linux, osx]
julia: [1.0, nightly]
matrix:
  allow_failures: [{julia: nightly}]
  fast_finish: true
notifications: {email: false}
addons:
  apt: {packages: [lua5.3-dev]}
  homebrew: {packages: [lua]}
jobs:
  include:
    - stage: Documentation
      julia: 1.0
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          Pkg.build("Lua");
          include("docs/make.jl");'
      after_success: skip
