name = "Lua"
uuid = "d2862c9e-00f7-11e9-2f10-efd208d22469"
authors = ["Chris de Graaf <chrisadegraaf@gmail.com>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
